services:
  sionna-api:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    container_name: aerpaw-sionna-api
    gpus: all
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - SCENE_PATH=/app/scenes/lake-wheeler-scene.xml
    restart: unless-stopped
